---
ORACLE_BRIDGE_MODE: "ARBITRARY_MESSAGE"

ORACLE_LOG_LEVEL: info

COMMON_HOME_RPC_URL: "https://rpc.sigma1.artis.network"
COMMON_HOME_BRIDGE_ADDRESS: "0xcaF101181Ba5727B1F440A17c060dd7f93F4dD04"
ORACLE_HOME_RPC_POLLING_INTERVAL: 7000

COMMON_FOREIGN_RPC_URL: "https://rpc.xdaichain.com"
COMMON_FOREIGN_BRIDGE_ADDRESS: "0xA7f00545a90D1EFd6e01952D8E0bb799D152C71A"
ORACLE_FOREIGN_RPC_POLLING_INTERVAL: 15000

# 100 gwei
COMMON_HOME_GAS_PRICE_FALLBACK: 100000000000
COMMON_HOME_GAS_PRICE_FACTOR: 1
# don't
ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL: 600000000

# COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL: "https://gasprice.poa.network/"
# COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE: "fast"
COMMON_FOREIGN_GAS_PRICE_FALLBACK: 1000000000
COMMON_FOREIGN_GAS_PRICE_FACTOR: 1
# don't
ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL: 600000000

